spring.application.name=HiddenUkWeb

#Database
spring.datasource.url=jdbc:mysql://localhost:3306/hiddenuk
spring.datasource.username=root
spring.datasource.password=Akhil@987
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

